### ISSUE TITLE
Lab 3: no module pysal.contrib

### ISSUE THREAD

**Issue by lheagy** [darribas/gds18#8] opened 2019-02-10 22:30 UTC
I looks like the API for pysal may have changed:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-1b56deea36c3> in <module>
      4 import geopandas as gpd
      5 import pysal as ps
----> 6 from pysal.contrib.viz import mapping as maps
      7 import palettable as pltt
      8 from seaborn import palplot

ModuleNotFoundError: No module named 'pysal.contrib'
```

This is a minor issues related to the JOSE review: openjournals/jose-reviews#42 (not a publication blocker)

**Comment by jsta** [comment] 2019-02-12 12:53
I can confirm getting the same error.

**Comment by darribas** [comment] 2019-02-28 17:58
Good catch! Since the course finished this year (December'18) and now, [we released](https://twitter.com/darribas/status/1090913357509607424) PySAL 2.0 which introduces a whole bunch of API changes. Since this iteration of the course was designed and delivered on PySAL 1.X, I've decided to leave it like that and pin to that version on the installer. Next year's iteration will be based on PySAL 2.X API.

[Closing for now but feel free to re-open if needed]

**Closed as completed by darribas** 2019-02-28 17:58 UTC
